### ISSUE TITLE
Settings Page Issues on Multisite

### ISSUE THREAD

**Issue by cspicuzza** [pods-framework/pods#2659]
I have a multisite setup where I built the foundation for everything with Pods then cloned it (using NS Cloner Pro)

The original version works fine but the cloned versions are having issues with one of the custom settings pages.  The code fields don't save data

This error shows in the inspector on the broken settings page:
GET http://spinefarmrecords.umg-wp3-dev.com/uk/wp-admin/dashicons-admin-home 404 admin.php?page=pods-settings-home&action=edit&do=save:1842 (not found)

Wordpress: 3.9.2
Pods: 2.5.1.1

Here's a screen cap for the pods settings page
![screen shot 2015-01-28 at 11 17 09 am](https://cloud.githubusercontent.com/assets/4442172/5944888/485c116a-a6df-11e4-9f7c-89eacf696784.png)

**Comment by Shelob9** [comment]
Can you please confirm that the Pod ID for your settings Pods is in fact 1842?

**Comment by cspicuzza** [comment]
?page=pods&action=edit&id=31

Looks to be a different ID.  Any suggestions on how I fix this?  Unfortunately I'm stuck in a situation where I don't have direct access to the db.

**Comment by Shelob9** [comment]
Without DB access this is not going to be very good solution. Here's a less than ideal work-around that should work:

* Do a full site back up just in case.
* Use the Pods Migrate Packages Component to export the settings Pod. Delete the Pod.
* Recreate the Pod using the package export file.

You will most likely loose the settings that are stored, but it shouldn't be to big of a deal to recreate them manually, since it's just one page.

**Comment by cspicuzza** [comment]
I'll give that a go, thanks

**Comment by cspicuzza** [comment]
I deleted the pod (didn't click the delete all items option) then reimported it with the migrate packages.  It looks like it created a new id but it does not match up with the id on the home settings page still causing the 404 error in the inspector.  

I also tried clearing the Pods Cache

**Comment by cspicuzza** [comment]
After further testing here's what I've tried.

1.) Removed the pod and items through the Pods Admin
2.) Cleared pods cache
3.) Reimported the Pod using the migration tool

The settings screen still shows an error in the inspector and the code field is unresponsive.  

Next I tried creating an entirely new pod settings page and added a test code field and test standard text field.  The text field works ok, this new code field is unresponsive just like the other.

The only way to adjust the code fields on these broken pods is through the multisite settings.

**Comment by Shelob9** [comment]
@cspicuzza Code field issues should have been fixed via #2665 Can you please test with the 2.x branch and see if that resolves the issue?

**Comment by cspicuzza** [comment]
That seemed to do it.  How soon will this branch go to production?

**Comment by Shelob9** [comment]
I'm not sure. We do not have a target release date. I wouldn't worry about using it. It's the same as the WPORG version + a bunch of bug fixes.

**Comment by cspicuzza** [comment]
As a heads up, even with the code field now working, the dashicons 404 not found error still exists in the inspector

" GET http://spinefarmrecords.dev/usa/wp-admin/dashicons-admin-home 404 (Not Found)"

**Comment by Shelob9** [comment]
@cspicuzza A core file returning 404 is a server config issue of some sort and not a Pods issue.
