### ISSUE TITLE
Migrate: Packages, the window is constrained by .pods-pick-values in pods-form.css

### ISSUE THREAD

**Issue by coding-panda** [pods-framework/pods#4509]
Please see the attached image.
![migrate-packages](https://user-images.githubusercontent.com/17201482/31465277-64a93306-aecb-11e7-8e96-7c416a02efb4.jpg)

**Comment by pglewis** [comment]
Can you test this on the 2.7 branch?  The CSS has been completely re-worked and I'm not seeing that rule nor the issue there.

**Comment by coding-panda** [comment]
Hi pglewis, thanks for your reply. I just downloaded 2.7 and tested, same problem, just the max-height is now 250px instead of 200px. I have this problem at work and at home.

**Comment by JoryHogeveen** [comment]
Now that is a big list of Pods!
Though this is fixed in my 2.7 dev site.
@coding-panda Could you re-check the 2.7 branch (and refresh your browser cache!)

**Comment by pglewis** [comment]
Also, if it persists even after ensuring you're not caching any old CSS, it would help to provide another screenshot showing where the rules are coming from.

**Comment by coding-panda** [comment]
@JoryHogeveen @pglewis Hi guys, Do I download 2.7 again from here: https://github.com/pods-framework/pods/tree/release/2.7? I did that and went to the settings to clear Pods cache, ctrl+F5, open pods-form.css and refreshed it, still the same. The good thing is that it can now display the Pods items in two columns without my interfering.

![migrate-packages-2](https://user-images.githubusercontent.com/17201482/31562588-fb39dfa8-b053-11e7-9537-02efa56813ce.jpg)

**Comment by pglewis** [comment]
`pods-form.css` should only be loading for the front-end after the reorganization of styles in 2.7.  It does not get loaded for me on the Migrate Packages page in 2.7.  

I would try it from an incognito/private browsers window to rule out or verify local browser caching issues.

**Comment by coding-panda** [comment]
It has been sorted. Thanks.
